POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "fullName": "Samuella Manye Aglago",
    "email": "samuellamanyeaglago@gmail.com",
    "password": "123456"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "samuellamanyeaglago@gmail.com",
    "password": "123456"
}

###
